version: 2
updates:
  # Check for updates to GitHub Actions every week.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # Check for updates to Go modules every week.
  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
