---
kind: pipeline
type: docker
name: default

steps:
  # Drone does not pull git tags by default
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  # Test your go app
  - name: test-unit
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go test -cover -race -v ./...

  # Smoke test
  - name: test-smoke
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w"
      - mkdir /smoke
      - mv stack /smoke
      - cd /smoke
      - ./stack

  # Run GoReleaser only on tags
  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl --fail --location --silent https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
      - ./bin/goreleaser
    when:
      event:
        - tag

# Save dependencies between steps
volumes:
  - name: deps
    temp: {}
