kind: pipeline
name: default
steps:
  # Drone does not pull git tags by default
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

# Test your go app
  - name: test
    image: golang
    volumes:
      - name: deps
        path: /go
        commands:
          - go test -race -v ./... -cover

# Run goreleaser only on tags
  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag

trigger:
  event:
  - pull_request

# Save dependencies between steps
volumes:
  - name: deps
    temp: {}
