name: Go

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - "**.go"
  pull_request:
    branches:
      - main
    paths:
      - "**.go"

jobs:
  build:
    name: Test and lint and build

    strategy:
      matrix:
        go-version:
          - 1.15.x
          - 1.16.x
          - 1.17.x
        platform:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update 'make' and run 'make all' on Linux
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get --only-upgrade install build-essential
          make all

      # Cannot use Docker on macOS runners: https://github.community/t/why-is-docker-not-installed-on-macos/17017
      - name: Install 'make' and run 'make test' on macOS
        if: ${{ matrix.platform == 'macos-latest' }}
        run: |
          brew install make
          /usr/local/opt/make/libexec/gnubin/make test

  release:
    name: Check that 'v*' tags are on the default branch, and release

    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Check out ${{ github.repository }} - all history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Confirm that the 'main' branch contains the '${{ github.ref }}' tag
        run: >
          git branch --all --contains '${{ github.ref }}' --no-column --format='%(refname)'
          | grep -c '\/main$'

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
